### ISSUE TITLE
Opensource license?

### ISSUE THREAD

**Issue by fire** [PCfVW/Simple-HTN-Planner#1]
Will you be opensourcing this?

**Comment by PCfVW** [comment]
You're speaking of the C++ code, right?
If so: Sure!
What do you want to do with it?
What kind of licence would suit your needs?

**Comment by PCfVW** [comment]
MIT License added.
When porting Dana Nau's Python code to C++ I discovered a couple of bugs in the Python code of some HTNs; Dana was busy so I fixed the code myself but was waiting for his approval which I got only a couple of weeks ago when (this time) I was really busy. Thanks for pinging me about this.

**Comment by fire** [comment]
Thanks!
